baseURL = "https://paulmatthews.dev/"
languageCode = "en-us"
title = "paulmatthews.dev"
theme = ["nix", "paulmatthews"]

[params]
  Name = "Paul Matthews"
  HeaderUsername = "paul"
  HeaderHostname = "pdmxdd"
  About = "Hey there! I'm Paul. I like programming, Linux, and DevOps. Professionaly, I design, create, manage, and often teach various tech curriculum. I am most experienced with DevOps curriculum (specifically in the AWS realm), but also have experience with Azure. I also teach introduction to web development courses that have included Python, Flask, Java, Spring, Node, HTML, CSS, and Angular. Feel free to reach out to me by email. Welcome!"
  ProfilePicture = "/profile-picture/profile-pic.png"
  Email = "paul@paulmatthews.dev"
  GithubID = "pdmxdd"
  GitlabID = "pdmxdd"

[menu]
  # [[menu.header]]
  #   name = "professional-projects"
  #   weight = 0
  #   url = "/projects/professional"
  # [[menu.header]]
  #   name = "personal-projects"
  #   weight = 0
  #   url = "/projects/personal"
  # [[menu.header]]
  #   name = "learn"
  #   weight = 0
  #   url = "/learn"
  [[menu.header]]
    name = "resume"
    weight = 0
    url = "/resume"
